name: flutter_tata_neu_assignment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.4
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  mockito: ^5.2.0
  flutter_svg: ^1.1.1+1
  provider: ^6.0.3
  get_it: ^7.2.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  built_value: ^8.1.4
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.1.1
  carousel_indicator: ^1.0.6
  intl: ^0.17.0
  connectivity:
  flutter_keyboard_visibility: ^5.3.0
  flutter_screenutil:


dev_dependencies:
  flutter_launcher_icons: "^0.9.3"
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - i18n/en.json
    - i18n/hi.json
    - assets/icons/
    - assets/images/
    - assets/jsons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
    - family: NotoSerif-Medium
      fonts:
        - asset: assets/fonts/NotoSerif-Medium.ttf